name: "Deploy para VPS"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Baixar o código"
        uses: "actions/checkout@v4"
      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v1
        with:
          host: "82.25.74.36"
          username: "root"
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/home/ventreminex"
      
      - name: "Build da daplicação"
        uses: appleboy/ssh-action@v1
        with:
          host: "82.25.74.36"
          username: "root"
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ventreminex
            sudo bash instal.sh
            chown -R www-data:www-data .